name: PR Checks

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '21'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Run Tests
        run: mvn test -B
