name: Release to Maven Central

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        default: '21'
        type: string
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name || github.ref_name }}
      - name: Extract version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Verify GPG setup
        run: |
          echo "Verifying GPG configuration..."
          gpg --list-secret-keys --keyid-format LONG
          echo "GPG version:"
          gpg --version | head -1
      - name: Deploy to Maven Central
        run: mvn clean deploy -B -U -DskipTests -Drevision=${VERSION}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
